#!/bin/bash
# 快速命令备忘录 - GitHub常用操作

echo "═══════════════════════════════════════════════════════"
echo "  GitHub 快速命令备忘录"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📦 首次上传（推荐使用一键脚本）"
echo "   ./一键上传.sh"
echo ""
echo "🔄 更新代码到GitHub"
echo "   git add ."
echo "   git commit -m \"更新说明\""
echo "   git push"
echo ""
echo "📥 从GitHub下载更新"
echo "   git pull"
echo ""
echo "📝 查看当前状态"
echo "   git status"
echo ""
echo "📜 查看提交历史"
echo "   git log --oneline"
echo ""
echo "🌿 分支操作"
echo "   git branch              # 查看分支"
echo "   git checkout -b 分支名  # 创建新分支"
echo "   git checkout main       # 切换到main分支"
echo ""
echo "↩️  撤销操作"
echo "   git reset HEAD~1        # 撤销最后一次commit"
echo "   git checkout -- 文件名  # 撤销文件修改"
echo ""
echo "🔍 查看差异"
echo "   git diff                # 查看未暂存的修改"
echo "   git diff --staged       # 查看已暂存的修改"
echo ""
echo "🏷️  标签管理"
echo "   git tag v1.0.0                    # 创建标签"
echo "   git push origin v1.0.0            # 推送标签"
echo "   git push origin --tags            # 推送所有标签"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "💡 提示："
echo "   • 每次修改后记得 commit 和 push"
echo "   • commit信息要清晰描述改动内容"
echo "   • 大改动前先创建新分支测试"
echo ""
echo "📞 需要帮助？"
echo "   查看: 上传到GitHub的步骤.md"
echo "   邮箱: fortyseven0629@gmail.com"
echo ""
